# nginx definetion file config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
---
# nginx definetion file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      containers:
        - name: nginx-ingress-controller
          image: <>

      args: 
        - /nginx-ingress-controller # nginx program is storead location command
        - --configmap=$ (POD_NAMESPACE)/nginx-ingress-controller
      env: 
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef: 
              fieldPath: metadat.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef: 
              fieldPath: metadat.name
      ports: 
        - name: http 
          containerPort: 80
        - name: https
          containerPort: 443
        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingres
spec:
  type: NodePort
  ports: 
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector: 
    name: nginx-ingres

---
# Service Account
kind: ServiceAccount
apiVersion: v1
metadata: 
  name: nginx-ingress-serviceaccount
   


